USE DATABASE EKP_DB;
USE SCHEMA RAG;

-- Example input table for one query embedding.
-- Insert here an ARRAY with exactly 384 FLOAT values generated by the same embedding model
-- that was used for document_chunks.embedding.
CREATE OR REPLACE TEMP TABLE query_embedding_tmp (
    embedding ARRAY NOT NULL
);

-- Example:
-- INSERT INTO query_embedding_tmp
-- SELECT PARSE_JSON('[0.0123, -0.0456, ... 382 more values ...]')::ARRAY;

WITH query_vector AS (
    SELECT embedding::VECTOR(FLOAT, 384) AS embedding
    FROM query_embedding_tmp
    LIMIT 1
)
SELECT
    dc.chunk_id,
    dc.document_id,
    dc.source_uri,
    dc.chunk_index,
    dc.chunk_text,
    VECTOR_COSINE_SIMILARITY(dc.embedding, q.embedding) AS similarity
FROM document_chunks AS dc
CROSS JOIN query_vector AS q
ORDER BY similarity DESC
LIMIT 10;
